#!/usr/bin/env python3
"""
Omega-1 Network Setup Wizard
============================

Manages Wi-Fi mode switching for Raspberry Pi:
- Access Point Mode (AP mode / Wi-Fi Direct)
- Client Mode (normal Wi-Fi)
- Headless SSH mode with static IP

Usage:
    sudo python3 network_wizard.py
    sudo omega-network ap
    sudo omega-network client
"""

import os
import sys
import subprocess
import shutil
import json
from pathlib import Path
from typing import Dict, Optional, Tuple

# Configuration constants
AP_SSID = "Omega1-AP"
AP_PASSWORD = "omegawifi123"
AP_IP = "192.168.4.1"
AP_DHCP_START = "192.168.4.2"
AP_DHCP_END = "192.168.4.20"
AP_SUBNET = "192.168.4.0"
AP_NETMASK = "255.255.255.0"

# File paths
HOSTAPD_CONF = "/etc/hostapd/hostapd.conf"
DNSMASQ_CONF = "/etc/dnsmasq.conf"
DHCPCD_CONF = "/etc/dhcpcd.conf"
HOSTAPD_DEFAULT = "/etc/default/hostapd"
NETWORK_STATE_FILE = "/etc/omega-network/state.json"
LOG_FILE = "/var/log/omega-network.log"

# Required packages
REQUIRED_PACKAGES = ["hostapd", "dnsmasq", "dhcpcd5"]


class Colors:
    """ANSI color codes for terminal output"""
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


def log(message: str, level: str = "INFO"):
    """Log message to file and stdout"""
    log_entry = f"[{level}] {message}\n"
    try:
        with open(LOG_FILE, "a") as f:
            f.write(log_entry)
    except PermissionError:
        pass  # Skip file logging if no permission
    
    if level == "ERROR":
        print(f"{Colors.FAIL}{log_entry.strip()}{Colors.ENDC}")
    elif level == "WARNING":
        print(f"{Colors.WARNING}{log_entry.strip()}{Colors.ENDC}")
    elif level == "SUCCESS":
        print(f"{Colors.OKGREEN}{log_entry.strip()}{Colors.ENDC}")
    else:
        print(log_entry.strip())


def check_root():
    """Ensure script is run as root"""
    if os.geteuid() != 0:
        log("This script must be run as root (use sudo)", "ERROR")
        sys.exit(1)


def run_command(cmd: list, check: bool = True) -> Tuple[bool, str]:
    """Run shell command and return success status and output"""
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=check
        )
        return True, result.stdout
    except subprocess.CalledProcessError as e:
        return False, e.stderr


def check_package_installed(package: str) -> bool:
    """Check if a package is installed"""
    success, _ = run_command(["dpkg", "-l", package], check=False)
    return success


def install_packages():
    """Install required packages if not present"""
    log("Checking for required packages...")
    
    missing_packages = []
    for package in REQUIRED_PACKAGES:
        if not check_package_installed(package):
            missing_packages.append(package)
            log(f"Missing package: {package}", "WARNING")
    
    if missing_packages:
        log(f"Installing packages: {', '.join(missing_packages)}")
        success, output = run_command(
            ["apt-get", "update"],
            check=False
        )
        if not success:
            log(f"Failed to update package list: {output}", "ERROR")
            return False
        
        success, output = run_command(
            ["apt-get", "install", "-y"] + missing_packages,
            check=False
        )
        if not success:
            log(f"Failed to install packages: {output}", "ERROR")
            return False
        
        log("Packages installed successfully", "SUCCESS")
    else:
        log("All required packages are installed", "SUCCESS")
    
    return True


def create_directory(path: str):
    """Create directory if it doesn't exist"""
    Path(path).mkdir(parents=True, exist_ok=True)


def backup_file(filepath: str) -> bool:
    """Backup existing configuration file"""
    if os.path.exists(filepath):
        backup_path = f"{filepath}.backup"
        try:
            shutil.copy2(filepath, backup_path)
            log(f"Backed up {filepath} to {backup_path}")
            return True
        except Exception as e:
            log(f"Failed to backup {filepath}: {e}", "WARNING")
            return False
    return True


def write_hostapd_config():
    """Create hostapd configuration for AP mode"""
    log("Creating hostapd configuration...")
    
    backup_file(HOSTAPD_CONF)
    create_directory(os.path.dirname(HOSTAPD_CONF))
    
    config = f"""# Omega-1 Access Point Configuration
# Generated by Omega Network Wizard

interface=wlan0
driver=nl80211
ssid={AP_SSID}
hw_mode=g
channel=7
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase={AP_PASSWORD}
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
"""
    
    try:
        with open(HOSTAPD_CONF, "w") as f:
            f.write(config)
        log(f"Created {HOSTAPD_CONF}", "SUCCESS")
        return True
    except Exception as e:
        log(f"Failed to write {HOSTAPD_CONF}: {e}", "ERROR")
        return False


def write_dnsmasq_config():
    """Create dnsmasq configuration for DHCP"""
    log("Creating dnsmasq configuration...")
    
    backup_file(DNSMASQ_CONF)
    
    config = f"""# Omega-1 DHCP Configuration
# Generated by Omega Network Wizard

interface=wlan0
dhcp-range={AP_DHCP_START},{AP_DHCP_END},{AP_NETMASK},12h
dhcp-option=3,{AP_IP}
dhcp-option=6,{AP_IP}
server=8.8.8.8
log-queries
log-dhcp
"""
    
    try:
        with open(DNSMASQ_CONF, "w") as f:
            f.write(config)
        log(f"Created {DNSMASQ_CONF}", "SUCCESS")
        return True
    except Exception as e:
        log(f"Failed to write {DNSMASQ_CONF}: {e}", "ERROR")
        return False


def write_dhcpcd_config_ap_mode():
    """Update dhcpcd.conf for AP mode (static IP)"""
    log("Updating dhcpcd configuration for AP mode...")
    
    backup_file(DHCPCD_CONF)
    
    # Read existing config
    existing_config = ""
    if os.path.exists(DHCPCD_CONF):
        with open(DHCPCD_CONF, "r") as f:
            existing_config = f.read()
    
    # Remove any existing wlan0 configuration
    lines = existing_config.split("\n")
    filtered_lines = []
    skip_until_blank = False
    
    for line in lines:
        if "interface wlan0" in line.lower():
            skip_until_blank = True
            continue
        if skip_until_blank and line.strip() == "":
            skip_until_blank = False
            continue
        if skip_until_blank:
            continue
        filtered_lines.append(line)
    
    # Add AP mode configuration
    ap_config = f"""
# Omega-1 AP Mode Configuration (added by network wizard)
interface wlan0
static ip_address={AP_IP}/24
nohook wpa_supplicant
"""
    
    new_config = "\n".join(filtered_lines) + ap_config
    
    try:
        with open(DHCPCD_CONF, "w") as f:
            f.write(new_config)
        log(f"Updated {DHCPCD_CONF} for AP mode", "SUCCESS")
        return True
    except Exception as e:
        log(f"Failed to write {DHCPCD_CONF}: {e}", "ERROR")
        return False


def write_dhcpcd_config_client_mode():
    """Update dhcpcd.conf for client mode (DHCP)"""
    log("Updating dhcpcd configuration for client mode...")
    
    backup_file(DHCPCD_CONF)
    
    # Read existing config
    existing_config = ""
    if os.path.exists(DHCPCD_CONF):
        with open(DHCPCD_CONF, "r") as f:
            existing_config = f.read()
    
    # Remove AP mode configuration
    lines = existing_config.split("\n")
    filtered_lines = []
    skip_until_blank = False
    
    for line in lines:
        if "interface wlan0" in line.lower() and "Omega-1 AP Mode" in existing_config:
            skip_until_blank = True
            continue
        if skip_until_blank and line.strip() == "":
            skip_until_blank = False
            continue
        if skip_until_blank:
            continue
        filtered_lines.append(line)
    
    new_config = "\n".join(filtered_lines)
    
    try:
        with open(DHCPCD_CONF, "w") as f:
            f.write(new_config)
        log(f"Updated {DHCPCD_CONF} for client mode", "SUCCESS")
        return True
    except Exception as e:
        log(f"Failed to write {DHCPCD_CONF}: {e}", "ERROR")
        return False


def write_hostapd_default():
    """Configure hostapd default settings"""
    log("Configuring hostapd defaults...")
    
    backup_file(HOSTAPD_DEFAULT)
    
    config = f"""# Omega-1 Hostapd Default Configuration
# Generated by Omega Network Wizard

DAEMON_CONF="{HOSTAPD_CONF}"
"""
    
    try:
        with open(HOSTAPD_DEFAULT, "w") as f:
            f.write(config)
        log(f"Created {HOSTAPD_DEFAULT}", "SUCCESS")
        return True
    except Exception as e:
        log(f"Failed to write {HOSTAPD_DEFAULT}: {e}", "ERROR")
        return False


def save_network_state(mode: str):
    """Save current network mode to state file"""
    create_directory(os.path.dirname(NETWORK_STATE_FILE))
    
    state = {
        "mode": mode,
        "ap_ssid": AP_SSID,
        "ap_ip": AP_IP,
        "last_updated": subprocess.check_output(["date", "-Iseconds"]).decode().strip()
    }
    
    try:
        with open(NETWORK_STATE_FILE, "w") as f:
            json.dump(state, f, indent=2)
        log(f"Saved network state: {mode}")
        return True
    except Exception as e:
        log(f"Failed to save network state: {e}", "WARNING")
        return False


def load_network_state() -> Optional[Dict]:
    """Load network state from file"""
    if os.path.exists(NETWORK_STATE_FILE):
        try:
            with open(NETWORK_STATE_FILE, "r") as f:
                return json.load(f)
        except Exception as e:
            log(f"Failed to load network state: {e}", "WARNING")
    return None


def stop_services():
    """Stop network services"""
    log("Stopping network services...")
    
    services = ["hostapd", "dnsmasq"]
    for service in services:
        success, _ = run_command(["systemctl", "stop", service], check=False)
        if success:
            log(f"Stopped {service}")
        else:
            log(f"Service {service} was not running or failed to stop", "WARNING")


def enable_ap_mode():
    """Enable Access Point mode"""
    log("=" * 60)
    log("Enabling Access Point Mode", "SUCCESS")
    log("=" * 60)
    
    if not install_packages():
        return False
    
    if not write_hostapd_config():
        return False
    
    if not write_dnsmasq_config():
        return False
    
    if not write_dhcpcd_config_ap_mode():
        return False
    
    if not write_hostapd_default():
        return False
    
    # Stop wpa_supplicant (interferes with AP mode)
    log("Stopping wpa_supplicant...")
    run_command(["systemctl", "stop", "wpa_supplicant"], check=False)
    run_command(["systemctl", "disable", "wpa_supplicant"], check=False)
    
    # Restart dhcpcd to apply static IP
    log("Restarting dhcpcd...")
    run_command(["systemctl", "restart", "dhcpcd"], check=False)
    
    # Wait for interface to be ready
    import time
    time.sleep(3)
    
    # Start AP services
    log("Starting hostapd and dnsmasq...")
    run_command(["systemctl", "enable", "hostapd"], check=False)
    run_command(["systemctl", "enable", "dnsmasq"], check=False)
    run_command(["systemctl", "start", "hostapd"], check=False)
    run_command(["systemctl", "start", "dnsmasq"], check=False)
    
    save_network_state("ap")
    
    log("=" * 60)
    log("Access Point Mode Enabled!", "SUCCESS")
    log(f"SSID: {AP_SSID}", "SUCCESS")
    log(f"Password: {AP_PASSWORD}", "SUCCESS")
    log(f"Pi IP: {AP_IP}", "SUCCESS")
    log("=" * 60)
    log("Connect to Omega1-AP and SSH: omega1@192.168.4.1")
    
    return True


def enable_client_mode():
    """Enable Wi-Fi Client mode"""
    log("=" * 60)
    log("Enabling Wi-Fi Client Mode", "SUCCESS")
    log("=" * 60)
    
    # Stop AP services
    stop_services()
    
    # Disable AP services
    run_command(["systemctl", "disable", "hostapd"], check=False)
    run_command(["systemctl", "disable", "dnsmasq"], check=False)
    
    # Update dhcpcd for client mode
    if not write_dhcpcd_config_client_mode():
        return False
    
    # Enable wpa_supplicant for client mode
    log("Enabling wpa_supplicant...")
    run_command(["systemctl", "enable", "wpa_supplicant"], check=False)
    run_command(["systemctl", "start", "wpa_supplicant"], check=False)
    
    # Restart dhcpcd to get DHCP IP
    log("Restarting dhcpcd...")
    run_command(["systemctl", "restart", "dhcpcd"], check=False)
    
    save_network_state("client")
    
    log("=" * 60)
    log("Client Mode Enabled!", "SUCCESS")
    log("Pi will connect to your Wi-Fi network", "SUCCESS")
    log("=" * 60)
    
    return True


def show_network_status():
    """Display current network status"""
    log("=" * 60)
    log("Network Status", "SUCCESS")
    log("=" * 60)
    
    state = load_network_state()
    if state:
        log(f"Current Mode: {state.get('mode', 'unknown').upper()}")
        if state.get('mode') == 'ap':
            log(f"AP SSID: {state.get('ap_ssid', AP_SSID)}")
            log(f"AP IP: {state.get('ap_ip', AP_IP)}")
    
    # Check service status
    log("\nService Status:")
    services = ["hostapd", "dnsmasq", "dhcpcd", "wpa_supplicant"]
    for service in services:
        success, output = run_command(
            ["systemctl", "is-active", service],
            check=False
        )
        status = "ACTIVE" if success else "INACTIVE"
        log(f"  {service}: {status}")
    
    # Check wlan0 IP
    log("\nInterface Status:")
    success, output = run_command(["ip", "addr", "show", "wlan0"], check=False)
    if success:
        log(f"wlan0:\n{output}")
    else:
        log("wlan0: Not configured", "WARNING")
    
    log("=" * 60)


def validate_ap_config() -> bool:
    """Validate AP configuration files"""
    log("Validating AP configuration...")
    
    checks = [
        (os.path.exists(HOSTAPD_CONF), f"{HOSTAPD_CONF} exists"),
        (os.path.exists(DNSMASQ_CONF), f"{DNSMASQ_CONF} exists"),
        (os.path.exists(HOSTAPD_DEFAULT), f"{HOSTAPD_DEFAULT} exists"),
    ]
    
    all_valid = True
    for check, message in checks:
        if check:
            log(f"✓ {message}", "SUCCESS")
        else:
            log(f"✗ {message}", "ERROR")
            all_valid = False
    
    # Check hostapd config content
    if os.path.exists(HOSTAPD_CONF):
        with open(HOSTAPD_CONF, "r") as f:
            content = f.read()
            if AP_SSID in content and AP_PASSWORD in content:
                log("✓ hostapd.conf contains correct SSID and password", "SUCCESS")
            else:
                log("✗ hostapd.conf missing SSID or password", "ERROR")
                all_valid = False
    
    return all_valid


def validate_hostapd_running() -> bool:
    """Validate that hostapd is running with correct config"""
    success, output = run_command(["systemctl", "is-active", "hostapd"], check=False)
    if not success:
        log("✗ hostapd is not running", "ERROR")
        return False
    
    log("✓ hostapd is running", "SUCCESS")
    
    # Check if it's using correct config
    success, output = run_command(["systemctl", "status", "hostapd"], check=False)
    if HOSTAPD_CONF in output:
        log("✓ hostapd using correct config file", "SUCCESS")
        return True
    else:
        log("⚠ hostapd config file may be incorrect", "WARNING")
        return False


def validate_wlan0_ip() -> bool:
    """Validate that wlan0 has correct static IP"""
    success, output = run_command(["ip", "addr", "show", "wlan0"], check=False)
    if not success:
        log("✗ wlan0 interface not found", "ERROR")
        return False
    
    if AP_IP in output:
        log(f"✓ wlan0 has correct IP: {AP_IP}", "SUCCESS")
        return True
    else:
        log(f"✗ wlan0 does not have IP {AP_IP}", "ERROR")
        return False


def validate_dhcp_service() -> bool:
    """Validate DHCP service is working"""
    success, output = run_command(["systemctl", "is-active", "dnsmasq"], check=False)
    if success:
        log("✓ dnsmasq is running", "SUCCESS")
        return True
    else:
        log("✗ dnsmasq is not running", "ERROR")
        return False


def run_full_validation():
    """Run all validation checks"""
    log("=" * 60)
    log("Running Network Validation", "SUCCESS")
    log("=" * 60)
    
    state = load_network_state()
    mode = state.get("mode", "unknown") if state else "unknown"
    
    if mode == "ap":
        results = [
            validate_ap_config(),
            validate_hostapd_running(),
            validate_wlan0_ip(),
            validate_dhcp_service(),
        ]
        
        if all(results):
            log("\n✓ All AP mode validations passed!", "SUCCESS")
            return True
        else:
            log("\n✗ Some validations failed", "ERROR")
            return False
    else:
        log(f"Current mode is '{mode}', skipping AP validations")
        return True


def interactive_menu():
    """Interactive CLI menu"""
    while True:
        print("\n" + "=" * 60)
        print(f"{Colors.BOLD}Omega-1 Network Wizard{Colors.ENDC}")
        print("=" * 60)
        print("1. Enable AP mode (field mode)")
        print("2. Enable Wi-Fi client mode (home mode)")
        print("3. Show network status")
        print("4. Regenerate configs")
        print("5. Run validation")
        print("6. Exit")
        print("=" * 60)
        
        choice = input(f"{Colors.OKCYAN}Select option (1-6): {Colors.ENDC}").strip()
        
        if choice == "1":
            enable_ap_mode()
        elif choice == "2":
            enable_client_mode()
        elif choice == "3":
            show_network_status()
        elif choice == "4":
            log("Regenerating configurations...")
            enable_ap_mode()  # Regenerate AP configs
        elif choice == "5":
            run_full_validation()
        elif choice == "6":
            log("Exiting...")
            break
        else:
            log("Invalid option. Please select 1-6.", "WARNING")


def main():
    """Main entry point"""
    check_root()
    
    if len(sys.argv) > 1:
        command = sys.argv[1].lower()
        
        if command == "ap":
            enable_ap_mode()
        elif command == "client":
            enable_client_mode()
        elif command == "status":
            show_network_status()
        elif command == "validate":
            run_full_validation()
        else:
            log(f"Unknown command: {command}", "ERROR")
            log("Usage: sudo python3 network_wizard.py [ap|client|status|validate]", "ERROR")
            sys.exit(1)
    else:
        interactive_menu()


if __name__ == "__main__":
    main()

