[pytest]
addopts =
    --ignore=tests/unit/test_autonomous_driving.py
    --ignore=tests/unit/test_autonomous_driving_with_astar.py
    --ignore=tests/unit/test_camera_publisher.py
    --ignore=tests/unit/test_line_tracking_publisher.py
    --ignore=tests/unit/test_sensor_fusion.py
    --ignore=tests/unit/test_ultrasonic_publisher.py
    --ignore=tests/unit/test_start_sensors.py
    --ignore=tests/unit/test_battery_monitor.py
    --ignore=tests/unit/test_d_star_lite_ros.py
    --ignore=tests/unit/test_d_star_lite.py
    --ignore=tests/unit/test_config_manager.py
    --ignore=tests/unit/test_log_sensor_data.py
    --ignore=tests/unit/test_visualize_sensor_data.py
    --ignore=tests/unit/test_simulated_sensors.py
